-- ============================================================
-- GUARDIÃ DO FOGO
-- Cap 1 - Atividade - BANCO DE DADOS NA SOCIEDADE 5.0
-- Script 01 - Criação das tabelas Oracle
-- ============================================================

CREATE TABLE usuario (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(120) NOT NULL,
    email           VARCHAR2(180) NOT NULL,
    perfil          VARCHAR2(30) DEFAULT 'USUARIO' NOT NULL,
    data_cadastro   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('USUARIO', 'GESTOR', 'DEFESA_CIVIL'))
);

CREATE TABLE foco_queimada (
    id_foco             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cidade              VARCHAR2(100) NOT NULL,
    estado              CHAR(2) NOT NULL,
    latitude            NUMBER(10,6) NOT NULL,
    longitude           NUMBER(10,6) NOT NULL,
    satelite            VARCHAR2(50),
    fonte               VARCHAR2(100),
    confianca           NUMBER(5,2) NOT NULL,
    brilho              NUMBER(8,2),
    distancia_km        NUMBER(8,2) NOT NULL,
    data_deteccao       TIMESTAMP NOT NULL,
    processado          CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_foco_queimada PRIMARY KEY (id_foco),
    CONSTRAINT ck_foco_confianca CHECK (confianca BETWEEN 0 AND 100),
    CONSTRAINT ck_foco_distancia CHECK (distancia_km >= 0),
    CONSTRAINT ck_foco_processado CHECK (processado IN ('S', 'N'))
);

CREATE TABLE leitura_ambiental (
    id_leitura          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_foco             NUMBER NOT NULL,
    temperatura_c       NUMBER(5,2),
    umidade_percentual  NUMBER(5,2),
    velocidade_vento    NUMBER(6,2),
    data_leitura        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_leitura_ambiental PRIMARY KEY (id_leitura),
    CONSTRAINT fk_leitura_foco FOREIGN KEY (id_foco) REFERENCES foco_queimada (id_foco),
    CONSTRAINT ck_leitura_umidade CHECK (
        umidade_percentual IS NULL OR umidade_percentual BETWEEN 0 AND 100
    )
);

CREATE TABLE alerta (
    id_alerta        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_foco          NUMBER NOT NULL,
    nivel_risco      VARCHAR2(20) NOT NULL,
    mensagem         VARCHAR2(500) NOT NULL,
    status           VARCHAR2(20) DEFAULT 'ABERTO' NOT NULL,
    data_criacao     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_alerta PRIMARY KEY (id_alerta),
    CONSTRAINT fk_alerta_foco FOREIGN KEY (id_foco) REFERENCES foco_queimada (id_foco),
    CONSTRAINT ck_alerta_nivel CHECK (nivel_risco IN ('BAIXO', 'MEDIO', 'ALTO', 'CRITICO')),
    CONSTRAINT ck_alerta_status CHECK (status IN ('ABERTO', 'EM_ANALISE', 'ENCERRADO'))
);

CREATE INDEX idx_foco_data ON foco_queimada (data_deteccao);
CREATE INDEX idx_foco_processado ON foco_queimada (processado);
CREATE INDEX idx_alerta_foco ON alerta (id_foco);
CREATE INDEX idx_leitura_foco ON leitura_ambiental (id_foco);
